# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
################## Base ##################
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
################## iSort ##################
-   repo: https://github.com/PyCQA/isort
    rev: 5.9.2
    hooks:
    -   id: isort
################## Pylint ##################
#-   repo: https://github.com/PyCQA/pylint
#    rev: v2.9.5
#    hooks:
#    -   id: pylint
################## Flake8 ##################
#-   repo: https://github.com/PyCQA/flake8
#    rev: 3.8.3
#    hooks:
#    -   id: flake8
################## Mypy ##################
#-   repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v0.910
#    hooks:
#    -   id: mypy
################## Check-Manifest ##################
-   repo: https://github.com/mgedmin/check-manifest
    rev: '0.46'
    hooks:
    -   id: check-manifest
