language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"

# command to install dependencies
install:
  - pip install pytest coverage pytest-cov
  - pip install .

# command to run tests
script:
  - pytest

after_success:
  - bash <(curl -s https://codecov.io/bash)
