language: python
os: linux
dist: bionic
python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"

# command to install dependencies
install:
  - pip install pytest pytest-cov pandas
  - pip install .

# command to run tests
script:
  - pytest

after_success:
  - bash <(curl -s https://codecov.io/bash)
